spring:
  application:
    name: midas
  profiles:
    active: dev
server:
  undertow:
      max-http-post-size: 0
      buffer-size: 1024
  # 是否分配的直接内存
      direct-buffers: true
  servlet:
    context-path: /midas
  error:
    include-stacktrace: always
    include-exception: true
logging:
  level:
    com.zero.midas.remote: info
    com.zero.midas.mapper: info
mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
feign:
  httpclient:
    connection-timeout: 30000
    enabled: false
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
